[package]
name = "deploy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = { version = "0.22.0", features = ["default"] }
crossterm = { version = "0.26", features = ["event-stream"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.183", features = ["derive"] }
russh = { version = "0.38.0" }
russh-keys = { version = "0.38.0" }
serde_json = "1.0.105"
futures = "0.3.28"
tar = "0.4"
flate2 = "1.0.27"
async-trait = "0.1.73"
anyhow = "1.0.75"
