name: Build

on:
  push:
    branches:
      - master

jobs:
  windows-x86_64:
    name: windows x86_64
    runs-on: windows-latest
    env:
      build_toolchain: x86_64-pc-windows-msvc
      build_executable: deploy.exe
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ env.build_toolchain }}
      - run: cargo build --target=${{ build_toolchain }} --release
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ build_executable }}
          path: target/${{ build_toolchain }}/release/${{ build_executable }}

  apple-darwin-aarch64:
    name: apple darwin aarch64
    runs-on: macos-latest
    env:
      build_toolchain: aarch64-apple-darwin
      build_executable: deploy
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ env.build_toolchain }}
      - run: cargo build --target=${{ build_toolchain }} --release
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ build_executable }}
          path: target/${{ build_toolchain }}/release/${{ build_executable }}

  linux-x86_64:
    name: linux x86_64
    runs-on: ubuntu-latest
    env:
      build_toolchain: x86_64-unknown-linux-gnu
      build_executable: deploy
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ env.build_toolchain }}
      - run: cargo build --target=${{ build_toolchain }} --release
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ build_executable }}
          path: target/${{ build_toolchain }}/release/${{ build_executable }}

  linux-aarch64:
    name: linux aarch64
    runs-on: ubuntu-latest
    env:
      build_toolchain: aarch64-unknown-linux-gnu
      build_executable: deploy
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ env.build_toolchain }}
      - run: cargo build --target=${{ build_toolchain }} --release
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ build_executable }}
          path: target/${{ build_toolchain }}/release/${{ build_executable }}